"""Creación de tablas

Revision ID: 2894f1365561
Revises: 
Create Date: 2025-04-03 22:48:21.296647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2894f1365561'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libreria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('editorial', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_digital', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('libros')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros',
    sa.Column('libros_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('libros_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('libros_editorial', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('libros_anio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('libros_genero', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('libros_precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('libros_forma_digital', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint('libros_precio >= 0::numeric', name='libros_libros_precio_check'),
    sa.PrimaryKeyConstraint('libros_id', name='libros_pkey'),
    sa.UniqueConstraint('libros_name', name='libros_libros_name_key')
    )
    op.drop_table('libreria')
    # ### end Alembic commands ###
